name: Send Mocha test results to New Relic
description: Send Mocha test results to New Relic Log API
author: Pavel Saman
branding:
  icon: share
  color: green

inputs:
  new-relic-license-key:
    description: New Relic API ingest key
    required: true
  test-result-filename:
    description: Filename with test results
    required: false
    default: './results.json'
  fail-pipeline:
    description: Whether to fail the pipeline when something goes wrong in this action
    required: false
    default: '0'
  verbose-log:
    description: Print verbose messages to log, useful for debugging
    required: false
    default: '0'
  upload-test-artifact:
    description: Whether to upload test artifact
    required: false
    default: '1'
  job-id:
    description: Custom job id of the job this action was called from
    required: false
  new-relic-dashboard-link:
    description: Link to New Relic dashboard that will be printed in step summary on Summary page
    required: false
  new-relic-api-url:
    description: New Relic Log API url
    required: false
    default: https://log-api.newrelic.com/log/v1

runs:
  using: 'node16'
  main: 'dist/index.js'
